### ISSUE TITLE
Can't launch the tool.

### ISSUE THREAD

**Issue by Loftaris** [sushibagel/PoE-Mechanic-Watch#13]
Can't seem to add a screenshot, essential it's Error in #include file ..... reminder.ahk
Call to nonexistent function

Specifically: SetWindowVol(AhkExe, NotificationVolume)
Line 67

I'm using AHK 1.1.34(latest) and all the files are in the folder they extracted themselves in.

**Comment by sushibagel** [comment]
When you run the tool did you use the "Start Me.ahk" file? Moving forward that one needs to be used to launch the tool rather than PoE Mechanic Watch.ahk. The Start Me file is essentially checking that a required support script is installed.

**Comment by sushibagel** [comment]
> Can't seem to add a screenshot, essential it's Error in #include file ..... reminder.ahk Call to nonexistent function
> 
> Specifically: SetWindowVol(AhkExe, NotificationVolume) Line 67
> 
> I'm using AHK 1.1.34(latest) and all the files are in the folder they extracted themselves in.

When you run the tool did you use the "Start Me.ahk" file? Moving forward that one needs to be used to launch the tool rather than PoE Mechanic Watch.ahk. The Start Me file is essentially checking that a required support script is installed.

**Comment by Loftaris** [comment]
Yeah, sorry.  I ran the watch mechanic and not the start me.  Missed where it said run start me first.  Maybe rename it to SetUpTool_RunFirst  or something, so us dumb ones don't mess it up ;)

**Comment by sushibagel** [comment]
> Yeah, sorry. I ran the watch mechanic and not the start me. Missed where it said run start me first. Maybe rename it to SetUpTool_RunFirst or something, so us dumb ones don't mess it up ;)

My fault. I actually forgot to mention it in the Readme, I've updated it. I like your suggestion and will try and change it to a more descriptive name for the next release.
