### ISSUE TITLE
Screen Flickering

### ISSUE THREAD

**Issue by Corrosivex** [sushibagel/PoE-Mechanic-Watch#41]
My screen permanently flicks every 3 - 4 secs aprox whenever I've the script open. ( The Overlay is open but not showed in the video )

https://youtu.be/n4ZfxG2UdNA

**Comment by sushibagel** [comment]
> My screen permanently flicks every 3 - 4 secs aprox whenever I've the script open. ( The Overlay is open but not showed in the video )
> 
> https://youtu.be/n4ZfxG2UdNA

Hello, I think I see the flickering you're talking about. Are you able to do a full monitor capture so that I can see the overlay also? 

I have a suspicion of what may be happening but I don't know for sure.
- When the flicker happens does it seem to be refreshing the overlay? 
- Are you using any transparency on the overlay? 
- Also do you have any additional overlays active? ( other apps)

**Comment by Corrosivex** [comment]
Hello, I think I see the flickering you're talking about. Are you able to do a full monitor capture so that I can see the overlay also?

Here is the vid: https://youtu.be/EYRQ3cBO7f8

When the flicker happens does it seem to be refreshing the overlay? It could be the cause.
Are you using any transparency on the overlay? Nope, by default.
Also do you have any additional overlays active? ( other apps) No, just Windows Defender and now the software to do the full screen recording ( before I used the Xbox game bar thing )

**Comment by Corrosivex** [comment]
> > My screen permanently flicks every 3 - 4 secs aprox whenever I've the script open. ( The Overlay is open but not showed in the video )
> > https://youtu.be/n4ZfxG2UdNA
> 
> Hello, I think I see the flickering you're talking about. Are you able to do a full monitor capture so that I can see the overlay also?
> 
> I have a suspicion of what may be happening but I don't know for sure.
> 
> * When the flicker happens does it seem to be refreshing the overlay?
> * Are you using any transparency on the overlay?
> * Also do you have any additional overlays active? ( other apps)

Here is the video with the whole screen:
https://youtu.be/EYRQ3cBO7f8
* It could be the refreshing thing.
* Nope, my transparency is set by default
* Just Windows Defender and now the software to record the video ( In the 1st vid I used the Xbox game bar thing )

**Comment by sushibagel** [comment]
> > > My screen permanently flicks every 3 - 4 secs aprox whenever I've the script open. ( The Overlay is open but not showed in the video )
> > > https://youtu.be/n4ZfxG2UdNA
> > 
> > Hello, I think I see the flickering you're talking about. Are you able to do a full monitor capture so that I can see the overlay also?
> > 
> > I have a suspicion of what may be happening but I don't know for sure.
> > 
> > * When the flicker happens does it seem to be refreshing the overlay?
> > * Are you using any transparency on the overlay?
> > * Also do you have any additional overlays active? ( other apps)
> 
> Here is the video with the whole screen:
> https://youtu.be/EYRQ3cBO7f8
> * It could be the refreshing thing.
> * Nope, my transparency is set by default
> * Just Windows Defender and now the software to record the video ( In the 1st vid I used the Xbox game bar thing )

It doesn't seem to be refreshing the overlay when it's happening you'd see the overlay also flicker if it was. I've yet to try it at all on Windows 11 so part of me is wondering if that has something to do with it. I do have a system I can test it on later. In the meantime could you try adding a bit of transparency to the overlay and see if that makes any difference?

**Comment by Corrosivex** [comment]
> > > > My screen permanently flicks every 3 - 4 secs aprox whenever I've the script open. ( The Overlay is open but not showed in the video )
> > > > https://youtu.be/n4ZfxG2UdNA
> > > 
> > > 
> > > Hello, I think I see the flickering you're talking about. Are you able to do a full monitor capture so that I can see the overlay also?
> > > I have a suspicion of what may be happening but I don't know for sure.
> > > 
> > > * When the flicker happens does it seem to be refreshing the overlay?
> > > * Are you using any transparency on the overlay?
> > > * Also do you have any additional overlays active? ( other apps)
> > 
> > 
> > Here is the video with the whole screen:
> > https://youtu.be/EYRQ3cBO7f8
> > 
> > * It could be the refreshing thing.
> > * Nope, my transparency is set by default
> > * Just Windows Defender and now the software to record the video ( In the 1st vid I used the Xbox game bar thing )
> 
> It doesn't seem to be refreshing the overlay when it's happening you'd see the overlay also flicker if it was. I've yet to try it at all on Windows 11 so part of me is wondering if that has something to do with it. I do have a system I can test it on later. In the meantime could you try adding a bit of transparency to the overlay and see if that makes any difference?

Sure! Lowered the transparency value multiple times, with different values and the flickering keep happening.

**Comment by sushibagel** [comment]
> Sure! Lowered the transparency value multiple times, with different values and the flickering keep happening.

Thanks for checking that. I booted the game up on laptop with Windows 11 and even matched the graphics settings you showed in your first video and couldn't replicate your issue. You have a 6900 XT so the video card is probably not the issue and I'd assume you probably have a pretty decent CPU paired with a 6900 XT? Is it also safe to assume the game ran fine on this current patch on the machine you are using without the overlay on?

**Comment by Corrosivex** [comment]
> > Sure! Lowered the transparency value multiple times, with different values and the flickering keep happening.
> 
> Thanks for checking that. I booted the game up on laptop with Windows 11 and even matched the graphics settings you showed in your first video and couldn't replicate your issue. You have a 6900 XT so the video card is probably not the issue and I'd assume you probably have a pretty decent CPU paired with a 6900 XT? Is it also safe to assume the game ran fine on this current patch on the machine you are using without the overlay on?

Yes, I've a Ryzen 9 5900X. The game runs smooth, 60+ fps almost in every scenario. Without any visual bugs or something "weird"

**Comment by sushibagel** [comment]
This is a bit of a longshot but 

> Yes, I've a Ryzen 9 5900X. The game runs smooth, 60+ fps almost in every scenario. Without any visual bugs or something "weird"

This is a bit of a long shot but can you try deleting the line below in the file called "Overlay.ahk" it should be located in the Resources/Scripts folder at line 126. 

Gui, Overlay:+E0x02000000 +E0x00080000 ; WS_EX_COMPOSITED WS_EX_LAYERED

Once you've deleted the line close the script and restart it.

**Comment by Corrosivex** [comment]
> This is a bit of a longshot but
> 
> > Yes, I've a Ryzen 9 5900X. The game runs smooth, 60+ fps almost in every scenario. Without any visual bugs or something "weird"
> 
> This is a bit of a long shot but can you try deleting the line below in the file called "Overlay.ahk" it should be located in the Resources/Scripts folder at line 126.
> 
> Gui, Overlay:+E0x02000000 +E0x00080000 ; WS_EX_COMPOSITED WS_EX_LAYERED
> 
> Once you've deleted the line close the script and restart it.
> 
> Edit: if that doesn't work lets also try deleting: WinSet, TransColor, 1e1e1e %OverlayTransparency%, Overlay which should be a few lines below the other one.

I've deleted both lines and nothing. BUT after doing a "reinstall" I've found that ONLY when I turn on "Metamorph, Ritual or Eldirtch" is when the flickering appears. If I dont turn it on, it works fine.

Video for reference: https://youtu.be/lXoOVznu_cU

**Comment by sushibagel** [comment]
> I've deleted both lines and nothing. BUT after doing a "reinstall" I've found that ONLY when I turn on "Metamorph, Ritual or Eldirtch" is when the flickering appears. If I dont turn it on, it works fine.
> 
> Video for reference: https://youtu.be/lXoOVznu_cU

Oh interesting so it must have something to do with the screen searching. I bet the flicker is when a screen capture is actually happening. Let me do a bit more research and hopefully I will be able to figure out a solution. Just to confirm the first time you launched the script did you use the "Launcher.ahk"?

**Comment by Corrosivex** [comment]
Yes, I used it.

**Comment by Corrosivex** [comment]
> > I've deleted both lines and nothing. BUT after doing a "reinstall" I've found that ONLY when I turn on "Metamorph, Ritual or Eldirtch" is when the flickering appears. If I dont turn it on, it works fine.
> > Video for reference: https://youtu.be/lXoOVznu_cU
> 
> Oh interesting so it must have something to do with the screen searching. I bet the flicker is when a screen capture is actually happening. Let me do a bit more research and hopefully I will be able to figure out a solution. Just to confirm the first time you launched the script did you use the "Launcher.ahk"?

Yes I used it.

**Comment by sushibagel** [comment]
> Yes I used it.

Okay, I was just able to reproduce the flicker on my Win 11 system now too. So now I also have a means to test a bit on my end too. I'll see what I can do to get it fixed.

**Comment by sushibagel** [comment]
Hey sorry I haven't had a ton of time to work on this lately. Could you do me a favor and try setting the in-game renderer to DX12 instead of DX11 and see if that helps at all. I found that Lailloken-UI uses a similar method to capture the screen and was also having the flicker issue and there are reports that DX12 may solve the issue. 

https://github.com/Lailloken/Lailloken-UI/issues/306

**Comment by Corrosivex** [comment]
> Hey sorry I haven't had a ton of time to work on this lately. Could you do me a favor and try setting the in-game renderer to DX12 instead of DX11 and see if that helps at all. I found that Lailloken-UI uses a similar method to capture the screen and was also having the flicker issue and there are reports that DX12 may solve the issue.
> 
> [Lailloken/Lailloken-UI#306](https://github.com/Lailloken/Lailloken-UI/issues/306)

Hello! I haven't played since then. And now, after updating PoE and swapping to DX 11 now works without any flickering.

I've done some T1 maps to test it with the mechanics that "caused" back then the screen flicks and now they're being auto tracked without problems.

**Comment by Corrosivex** [comment]
> Hey sorry I haven't had a ton of time to work on this lately. Could you do me a favor and try setting the in-game renderer to DX12 instead of DX11 and see if that helps at all. I found that Lailloken-UI uses a similar method to capture the screen and was also having the flicker issue and there are reports that DX12 may solve the issue.
> 
> [Lailloken/Lailloken-UI#306](https://github.com/Lailloken/Lailloken-UI/issues/306)

Hello! I haven't played since then. And now, after updating PoE and swapping to DX 12 now works without any flickering.

I've done some T1 maps to test it with the mechanics that "caused" back then the screen flicks and now they're being auto tracked without problems.

**Comment by sushibagel** [comment]
> > Hey sorry I haven't had a ton of time to work on this lately. Could you do me a favor and try setting the in-game renderer to DX12 instead of DX11 and see if that helps at all. I found that Lailloken-UI uses a similar method to capture the screen and was also having the flicker issue and there are reports that DX12 may solve the issue.
> > 
> > [Lailloken/Lailloken-UI#306](https://github.com/Lailloken/Lailloken-UI/issues/306)
> 
> Hello! I haven't played since then. And now, after updating PoE and swapping to DX 12 now works without any flickering.
> 
> I've done some T1 maps to test it with the mechanics that "caused" back then the screen flicks and now they're being auto tracked without problems.
> 
> 

Awesome thanks for checking!
