### ISSUE TITLE
Error when double clicking Launcher.ahk

### ISSUE THREAD

**Issue by ArawnDA** [sushibagel/PoE-Mechanic-Watch#43]
Line Text: switch MyKey
Error: This line does not contain a recognizable action

It references line 2 in the ini.ahk  in the Scripts folder

Thanks

![launcher error](https://github.com/sushibagel/PoE-Mechanic-Watch/assets/25443225/ea594c33-4eff-4ac1-8710-a86a7b3f4d48)

**Comment by sushibagel** [comment]
Can you try re-uploading the image? The link isn't working for me.

**Comment by sushibagel** [comment]
Also just to make sure, are you launching it from within the folder with the rest of the contents?

**Comment by ArawnDA** [comment]
Yes 

![b668811f1541a780adeaa67242782e40](https://github.com/sushibagel/PoE-Mechanic-Watch/assets/25443225/01184ba2-976a-44d7-b28d-1c7ff971b068)

**Comment by ArawnDA** [comment]
I have AutoHotkey v1.1.26.01, would that matter?

**Comment by sushibagel** [comment]
> I have AutoHotkey v1.1.26.01, would that matter?

That's actually very helpful, thank you. That was going to be my next question. 

Is this your first time using PoE Mechanic Watch?

**Comment by ArawnDA** [comment]
No, I think the last tool version was v1.3.3. 

I'll update ahk to the latest v1 and see what happens

**Comment by ArawnDA** [comment]
BINGO!! That solved it! ahk v1.1.37.01

Thank you so much for the help and for the tool. Can't wait to use it and get back into poe.

**Comment by sushibagel** [comment]
Great! Glad that worked! Enjoy
